# hybris-mobian docker images build definition for Travis CI
# Contact: Eugenio "g7" Paolantonio <me@medesimo.eu>

os: linux
dist: focal

stages:
  - docker
  - manifest-creation

services:
  - docker

_docker_build_template: &docker_build_template
  stage: docker

  script:
    - ./src/build_docker_image.sh "${TRAVIS_JOB_NAME}"

  deploy:
    provider: script
    script:
      - ./src/push_docker_image.sh "${TRAVIS_JOB_NAME}"
    on:
      branch: master

_manifest_build: &manifest_build
  stage: manifest-creation

  script: skip

  deploy:
    provider: script
    script:
      - ./src/push_manifests.py
    on:
      branch: master

########################################################################

# Add new images here

jobs:
  include:
  # AMD64 (x86_64) image containing toolchains and essential build
  # tools
  - name: amd64/hybrismobian/build-essential:bullseye
    arch: amd64
    <<: *docker_build_template
  # ARM64 (AArch64) image containing toolchains and essential build
  # tools
  - name: arm64/hybrismobian/build-essential:bullseye
    arch: arm64-graviton2
    virt: vm # required to route the job to arm64-graviton2
    group: edge # required to route the job to arm64-graviton2
    <<: *docker_build_template

  #################################################################
  - name: manifest-build
    <<: *manifest_build
