# Pull latest Debian trixie
ARG ARCH=
FROM ${ARCH}/debian:trixie

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS yes
ENV DEBIAN_PRIORITY critical

# Required for https repositories
RUN apt-get update && apt-get install --yes ca-certificates

# Copy relevant repositories and keyrings
# Note: .dummy files used to keep the directory hierarchy in git are
# copied too, see moby/moby#26332
COPY repositories/trixie/all/* /etc/apt/sources.list.d/
COPY repositories/trixie/amd64/* /etc/apt/sources.list.d/

# Copy apt preferences
COPY preferences/trixie/* /etc/apt/preferences.d/

COPY keyrings/all/* /etc/apt/furilabs-gpg.d/
COPY keyrings/amd64/* /etc/apt/furilabs-gpg.d/

COPY common/apt.conf.d/* /etc/apt/apt.conf.d/

# Copy deployer for repo.furilabs.com
COPY extra/repo-furios-deploy.sh /usr/local/bin
COPY extra/repo-furios-sign.sh /usr/local/bin

# Add secondary architectures
RUN dpkg --add-architecture arm64 && dpkg --add-architecture armhf && dpkg --add-architecture i386

# Update and install
RUN apt-get update && apt-get install -y --allow-downgrades \
 build-essential \
 libncurses-dev \
 bash-completion \
 nano \
 devscripts \
 equivs \
 wget \
 openssh-client \
 rsync \
 mkbootimg \
 mkdtboimg \
 releng-tools \
 droidian-apt-config \
 droidian-archive-keyring \
 mobian-archive-keyring && \
 rm -f /etc/apt/sources.list.d/furilabs.list /etc/apt/sources.list.d/mobian.list && \
 apt-get dist-upgrade -y --allow-downgrades

# Patch dpkg-perl's Patch.pm to avoid overzealous checks
RUN \
	sed -i \
		"s|error(g_('diff %s modifies file %s through a symlink: %s')|warning(g_('diff %s modifies file %s through a symlink: %s')|" \
		/usr/share/perl5/Dpkg/Source/Patch.pm && \
	echo "libdpkg-perl hold" | dpkg --set-selections
