# syntax=docker/dockerfile:experimental

# Pull latest Debian forky
ARG ARCH=
FROM ${ARCH}/debian:forky AS builder

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS yes
ENV DEBIAN_PRIORITY critical

# Install debootstrap
RUN apt-get update && apt-get install -y debootstrap

# Run debootstrap
ARG MIRROR=http://debian.furios.io/
RUN debootstrap --arch=arm64 forky /rootfs $MIRROR

# Add custom apt configuration
RUN echo 'Acquire::Check-Valid-Until false;' > /rootfs/etc/apt/apt.conf.d/10custom-settings && \
    echo 'Acquire::https::Verify-Peer false;' >> /rootfs/etc/apt/apt.conf.d/10custom-settings && \
    echo 'Acquire::Check-Date false;' >> /rootfs/etc/apt/apt.conf.d/10custom-settings

# Required for https repositories
RUN chroot /rootfs apt-get update
RUN chroot /rootfs apt-get install --yes ca-certificates adduser

# Copy relevant repositories and keyrings
# Note: .dummy files used to keep the directory hierarchy in git are
# copied too, see moby/moby#26332
COPY repositories/forky/all/* /rootfs/etc/apt/sources.list.d/
COPY repositories/forky/arm64/* /rootfs/etc/apt/sources.list.d/

# Copy apt preferences
COPY preferences/forky/* /rootfs/etc/apt/preferences.d/

COPY keyrings/all/* /rootfs/etc/apt/furilabs-gpg.d/
COPY keyrings/arm64/* /rootfs/etc/apt/furilabs-gpg.d/

# Copy deployer for repo.furilabs.com
COPY extra/repo-furios-deploy.sh /rootfs/usr/local/bin
COPY extra/repo-furios-sign.sh /rootfs/usr/local/bin

COPY common/apt.conf.d/* /rootfs/etc/apt/apt.conf.d/

# Add secondary architectures
RUN chroot /rootfs dpkg --add-architecture arm64

# Update and install
RUN chroot /rootfs apt-get update 
RUN chroot /rootfs apt-get install -y --allow-downgrades \
    build-essential \
    libncurses-dev \
    bash-completion \
    nano \
    devscripts \
    equivs \
    wget \
    openssh-client \
    rsync \
    mkbootimg \
    mkdtboimg \
    releng-tools \
    furios-apt-config \
    furios-apt-config-krypton \
    furios-archive-keyring \
    runonce

RUN chroot /rootfs rm -f /etc/apt/sources.list.d/furilabs.list /etc/apt/sources.list.d/gst.sources /etc/apt/sources.list

# Start fresh with the debootstrapped system
FROM scratch
COPY --from=builder /rootfs /

WORKDIR /
