# furilabs docker images build definition for GitHub Actions

name: furilabs docker-images

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "59 23 */14 * *"

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          # AMD64 builds

          # Trixie
          - arch: amd64
            runner: ubuntu-24.04
            template: build-essential
            dist: trixie
            namespace: furilabs
          - arch: amd64
            runner: ubuntu-24.04
            template: rootfs-builder
            dist: trixie
            namespace: furilabs
          - arch: amd64
            runner: ubuntu-24.04
            template: aptly-intake
            dist: trixie
            namespace: furilabs

          # Forky
          - arch: amd64
            runner: ubuntu-24.04
            template: build-essential
            dist: forky
            namespace: furilabs
          - arch: amd64
            runner: ubuntu-24.04
            template: rootfs-builder
            dist: forky
            namespace: furilabs
          - arch: amd64
            runner: ubuntu-24.04
            template: aptly-intake
            dist: forky
            namespace: furilabs

          # ARM64 builds

          # Trixie
          - arch: arm64
            runner: ubuntu-24.04-arm
            template: build-essential
            dist: trixie
            namespace: furilabs
          - arch: arm64
            runner: ubuntu-24.04-arm
            template: rootfs-builder
            dist: trixie
            namespace: furilabs

          # Forky
          - arch: arm64
            runner: ubuntu-24.04-arm
            template: build-essential
            dist: forky
            namespace: furilabs
          - arch: arm64
            runner: ubuntu-24.04-arm
            template: rootfs-builder
            dist: forky
            namespace: furilabs

    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.template }}:${{ matrix.dist }} on ${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build
        run: ./src/build_docker_image.sh "${{ matrix.arch }}/${{ matrix.namespace }}/${{ matrix.template }}:${{ matrix.dist }}"

      - name: Deploy
        if: "${{ github.ref == 'refs/heads/master' }}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./src/push_docker_image.sh "${{ matrix.arch }}/${{ matrix.namespace }}/${{ matrix.template }}:${{ matrix.dist }}"
